/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLLT.from;

import Ketnoi.KetNoi;
import QLLT.DAO.DAO_QLSP;
import QLLT.classs.QLSP;
import QLLT.from.fromcon.chitietsp;
import QLLT.from.fromcon.suasanpham;
import QLLT.from.fromcon.themsp;
import static QLLT.from.sanpham.dongia;
import static QLLT.from.sanpham.hinh;
import static QLLT.from.sanpham.ma;
import static QLLT.from.sanpham.maloai;
import static QLLT.from.sanpham.mota;
import static QLLT.from.sanpham.soluong;
import static QLLT.from.sanpham.ten;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinh
 */
public class sanpham1 extends javax.swing.JPanel {

    DefaultTableModel model;
    public static String ma, maloai, ten, dongia, soluong, hinh,mota;
    Ketnoi.KetNoi cn=new KetNoi();
    QLSP n= new QLSP();
    
    /**
     * Creates new form sanpham1
     */
    public sanpham1() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPanesp = new javax.swing.JDesktopPane();
        bltthem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtdongia = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        jpn = new javax.swing.JPanel();
        lblhinh = new javax.swing.JLabel();
        txttim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsp = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        txtlsp = new javax.swing.JTextField();
        txtmasp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablephieunhap = new javax.swing.JTable();
        txttim2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jButton12 = new javax.swing.JButton();
        txttim3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jDesktopPanesp.setBackground(new java.awt.Color(240, 240, 240));

        bltthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        bltthem.setText("thêm");
        bltthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltthemActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        jButton3.setText("sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        jButton1.setText("xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtdongia.setBorder(javax.swing.BorderFactory.createTitledBorder("đơn giá"));

        txttensp.setBorder(javax.swing.BorderFactory.createTitledBorder("tên sản phẩm"));

        txtsoluong.setBorder(javax.swing.BorderFactory.createTitledBorder("số lượng"));

        jpn.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnLayout = new javax.swing.GroupLayout(jpn);
        jpn.setLayout(jpnLayout);
        jpnLayout.setHorizontalGroup(
            jpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );
        jpnLayout.setVerticalGroup(
            jpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhinh, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );

        txttim.setBorder(javax.swing.BorderFactory.createTitledBorder("tìm kiếm"));
        txttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimActionPerformed(evt);
            }
        });

        tblsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "masp", "tên sp", "mã loại", "giá bán", "giá nhập", "số lượng", "hình ảnh", "mô tả"
            }
        ));
        tblsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsp);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_replay_30px.png"))); // NOI18N
        jButton7.setText("làm mới");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtlsp.setBorder(javax.swing.BorderFactory.createTitledBorder("loại sản phẩm"));

        txtmasp.setBorder(javax.swing.BorderFactory.createTitledBorder("mã sản phẩm"));

        jButton2.setText("xem chi tiết sp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDesktopPanesp.setLayer(bltthem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txtdongia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txttensp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txtsoluong, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jpn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txttim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txtlsp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(txtmasp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPanesp.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanespLayout = new javax.swing.GroupLayout(jDesktopPanesp);
        jDesktopPanesp.setLayout(jDesktopPanespLayout);
        jDesktopPanespLayout.setHorizontalGroup(
            jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanespLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPanespLayout.createSequentialGroup()
                        .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPanespLayout.createSequentialGroup()
                        .addComponent(bltthem)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanespLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanespLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPanespLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPanespLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtlsp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        jDesktopPanespLayout.setVerticalGroup(
            jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanespLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bltthem)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(299, 299, 299))
            .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPanespLayout.createSequentialGroup()
                    .addContainerGap(250, Short.MAX_VALUE)
                    .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDesktopPanespLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtlsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jDesktopPanespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(46, 46, 46)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanesp)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanesp)
        );

        jTabbedPane1.addTab("sản phẩm", jPanel1);

        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        tablephieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablephieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablephieunhapMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablephieunhap);

        txttim2.setBorder(javax.swing.BorderFactory.createTitledBorder("tìm kiếm"));
        txttim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttim2ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jButton10.setText("tìm kiếm");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_replay_30px.png"))); // NOI18N
        jButton11.setText("làm mới");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addGap(9, 9, 9))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txttim2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttim2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(184, 184, 184))
        );

        jTabbedPane1.addTab("phiếu nhập", jPanel3);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jDesktopPane.setLayout(new java.awt.BorderLayout());

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        jButton12.setText("thêm");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        txttim3.setBorder(javax.swing.BorderFactory.createTitledBorder("tìm kiếm"));
        txttim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttim3ActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1", "2", "3"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        jButton4.setText("tìm kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        jButton13.setText("xóa");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        jButton14.setText("sửa");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_replay_30px.png"))); // NOI18N
        jButton15.setText("làm mới");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(64, 64, 64)
                        .addComponent(jButton13)
                        .addGap(77, 77, 77)
                        .addComponent(jButton14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txttim3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15)))
                .addGap(72, 72, 72)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addGap(241, 241, 241))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton14)
                            .addComponent(jButton13)
                            .addComponent(jButton12))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttim3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("loại sản phẩm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bltthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltthemActionPerformed

        themsp sp = new themsp();
        jDesktopPanesp.add(sp);
        sp.setVisible(true);
    }//GEN-LAST:event_bltthemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

//        suasanpham ssp = new suasanpham();
//        jDesktopPane1.add(ssp);
//        ssp.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimActionPerformed

    private void tblspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspMouseClicked
        // TODO add your handling code here:
        int row = tblsp.getSelectedRow();
        hienthi(row);
        jButton1.setEnabled(true);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_tblspMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        txttim.setText("");
        DAO_QLSP.dolentable(tblsp, 1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

//            cn = helper.hepper.ketnoi("qllaptop4");

            String sql = "DELETE dbo.sanpham WHERE masp LIKE ?";

        //    PreparedStatement pst = cn.prepareStatement(sql);
          //  pst.setString(1, table.getValueAt(table.getSelectedRow(), 0).toString());
//
            int hoi = JOptionPane.showConfirmDialog(this, "xóa sản phẩm");
            if (hoi == JOptionPane.YES_OPTION) {

              //  pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "xóa thành công");
                model.setRowCount(0);
          //      loaddatatable();

            } else {
                JOptionPane.showMessageDialog(this, "chưa xóa");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi xóa sp");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        DAO_QLSP.dolentable(tblsp, 1);
        jButton1.setEnabled(false);
        jButton3.setEnabled(false);
   
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
        String heder[] = {"Mã loại", "tên loại", "mô tả"};
        String data[][] = null;
        model = new DefaultTableModel(data, heder);
       // tablelsp.setModel(model);
//        cn = helper.hepper.ketnoi("qllaptop4");
        System.out.println("kết nối thành công");
          jButton1.setEnabled(false);
        jButton3.setEnabled(false);
     //   loaddatatableloaisp();
        
    }//GEN-LAST:event_jPanel2ComponentShown

    private void tablephieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablephieunhapMouseClicked
        // TODO add your handling code here:
      //  jButton8.setEnabled(true);
    }//GEN-LAST:event_tablephieunhapMouseClicked

    private void txttim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttim2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

//        try {
//            String sql = "SELECT * FROM dbo.phieunhap\n"
//            + "WHERE mapn LIKE ?";
//        //    PreparedStatement ptsm = cn.prepareStatement(sql);
//          //  ptsm.setString(1, txttim.getText());
//           // ResultSet rs = ptsm.executeQuery();
//
//            model.setRowCount(0);
//            while (rs.next()) {
//
//                Vector sp = new Vector();
//                sp.add(rs.getString(1));
//                sp.add(rs.getString(2));
//                sp.add(rs.getString(3));
//                sp.add(rs.getString(4));
//                sp.add(rs.getString(5));
//
//                model.addRow(sp);
//
//            }
//
//            table.setModel(model);
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm");
//        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        txttim.setText("");
       // loaddatatable();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:
        String heder[] = {"Mã PN", "MÃ NCC", "MÃ NV", "Ngày lập", "tổng tiền"};
        String data[][] = null;
        model = new DefaultTableModel(data, heder);
        tablephieunhap.setModel(model);
//        cn = helper.hepper.ketnoi("qllaptop4");
        System.out.println("kết nối thành công");
       // jButton8.setEnabled(false);
        //loaddatatablephieunhap();
       
    }//GEN-LAST:event_jPanel3ComponentShown

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
//        themloaisp tlsp=new themloaisp();
//        jDesktopPane1.add(tlsp);
//        tlsp.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txttim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttim3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttim3ActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked

        int row = tblsp.getSelectedRow();
        maloai=tblsp.getValueAt(row, 0).toString();
        ten=tblsp.getValueAt(row, 1).toString();

        mota=tblsp.getValueAt(row, 2).toString();
        jButton1.setEnabled(true);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_table1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//
//        try {
//            String sql = "SELECT * FROM dbo.loaisanpham\n" +
//            "      WHERE malsp LIKE ?";
//          //  PreparedStatement ptsm = cn.prepareStatement(sql);
//         //   ptsm.setString(1, txttim.getText());
//            ResultSet rs = .executeQuery();
//
//            model.setRowCount(0);
//            while(rs.next()){
//
//                Vector sp = new Vector();
//                sp.add(rs.getString(1));
//                sp.add(rs.getString(2));
//                sp.add(rs.getString(3));
//
//                model.addRow(sp);
//
//            }
//
//            table.setModel(model);
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Lỗi tìm kiếm");
//        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {

            //            cn = helper.hepper.ketnoi("qllaptop4");

            String sql = "DELETE dbo.loaisanpham WHERE malsp LIKE ?";

           // PreparedStatement pst = cn.prepareStatement(sql);
     //       pst.setString(1, table.getValueAt(table.getSelectedRow(), 0).toString());

            int hoi = JOptionPane.showConfirmDialog(this, "xóa loại sản phẩm");
            if (hoi == JOptionPane.YES_OPTION) {

     //           pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "xóa thành công");
                model.setRowCount(0);
             

            } else {
                JOptionPane.showMessageDialog(this, "chưa xóa");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi xóa sp");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
//        sualoaisp slsp=new sualoaisp();
//        jDesktopPane1.add(slsp);
//        slsp.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        txttim.setText("");
      
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chitietsp ctsp=new chitietsp();
        jDesktopPanesp.add(ctsp);
        ctsp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bltthem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JDesktopPane jDesktopPanesp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpn;
    private javax.swing.JLabel lblhinh;
    private javax.swing.JTable table1;
    private javax.swing.JTable tablephieunhap;
    private javax.swing.JTable tblsp;
    private javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtlsp;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txttim;
    private javax.swing.JTextField txttim2;
    private javax.swing.JTextField txttim3;
    // End of variables declaration//GEN-END:variables

   
    public void hinh(String hinh) {
        ImageIcon img = new ImageIcon("src\\img\\" + hinh);
        Image im = img.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(lblhinh.getWidth(), lblhinh.getHeight(), im.SCALE_SMOOTH));
        lblhinh.setIcon(icon);
    }

    public void hienthi(int row) {
        if (row < 0) {
            return;
        }
        txtmasp.setText(tblsp.getValueAt(row, 0).toString());
        txttensp.setText(tblsp.getValueAt(row, 1).toString());
        txtlsp.setText(tblsp.getValueAt(row, 2).toString());
        txtdongia.setText(tblsp.getValueAt(row, 3).toString());
        txtsoluong.setText(tblsp.getValueAt(row, 4).toString());

        hinh(tblsp.getValueAt(row, 6).toString());

        ma = tblsp.getValueAt(row, 0).toString();
        maloai = tblsp.getValueAt(row, 2).toString();
        ten = tblsp.getValueAt(row, 1).toString();
        dongia = tblsp.getValueAt(row, 3).toString();
        soluong = tblsp.getValueAt(row, 4).toString();
        hinh = tblsp.getValueAt(row, 5).toString();
        mota = tblsp.getValueAt(row, 6).toString();

    }
}
